import { useState } from "react";
import { X, Search, Images, Library, FolderKanban, Clock3, Puzzle, Square, Plus, Settings, LogOut, MessageSquare, Pencil, Trash2, Code2, Mic, Crown, Check } from "lucide-react";
import { useAuth } from "../context/AuthContext"; import { useApp } from "../context/AppContext"; import type { AppPage } from "../types";
interface SidebarProps { open:boolean; onClose:()=>void; onSettings:()=>void; page:AppPage; onNavigate:(page:AppPage)=>void; }
export default function Sidebar({open,onClose,onSettings,page,onNavigate}:SidebarProps){
  const {user,signOutUser}=useAuth(); const {chats,refreshChats,renameChat,deleteChat,setActiveChatId}=useApp(); const [editing,setEditing]=useState<string|null>(null); const [draft,setDraft]=useState(""); const [search,setSearch]=useState(""); const [busy,setBusy]=useState<string|null>(null);
  const newChat=()=>{setActiveChatId(null);onNavigate("home");onClose()};
  const visible=chats.filter(c=>c.title.toLowerCase().includes(search.toLowerCase()));
  const openChat=(id:string)=>{setActiveChatId(id);onNavigate("home");onClose()};
  const beginRename=(id:string,title:string)=>{setEditing(id);setDraft(title);};
  const saveRename=async(id:string)=>{const title=draft.trim();if(!title)return;setBusy(id);try{await renameChat(id,title);setEditing(null);}finally{setBusy(null);}};
  const removeChat=async(id:string)=>{setBusy(id);try{await deleteChat(id);}catch{}finally{setBusy(null);await refreshChats();}};
  const nav=(p:AppPage)=>{onNavigate(p);onClose()};
  return <aside className={`sidebar ${open?"sidebar-open":""}`}><div className="sidebar-top"><button className="brand-button" onClick={newChat}>DOG</button><button className="close-sidebar" onClick={onClose}><X size={22}/></button></div><button className="new-chat-button" onClick={newChat}><Plus size={18}/> New chat</button><div className="sidebar-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search chats"/></div><nav className="navigation">{([['home','Chats',MessageSquare],['images','Images',Images],['library','Library',Library],['projects','Projects',FolderKanban],['scheduled','Scheduled',Clock3],['plugins','Tools',Puzzle],['code','Code Builder',Code2],['voice','Voice AI',Mic],['pro','Pro',Crown]] as const).map(([id,label,Icon])=><button className={page===id?"active":""} key={id} onClick={()=>nav(id)}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sidebar-divider"/><div className="recents-title">Your chats</div><div className="recent-list">{visible.length===0?<div className="sidebar-empty">No chats yet</div>:visible.map(chat=><div className="recent-item" key={chat.id}><Square size={17}/>{editing===chat.id?<div className="rename-row"><input autoFocus value={draft} className="rename-input" onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void saveRename(chat.id);if(e.key==="Escape")setEditing(null)}}/><button onClick={()=>void saveRename(chat.id)} disabled={busy===chat.id} title="Save"><Check size={14}/></button></div>:<button className="recent-title-button" onClick={()=>openChat(chat.id)}><strong>{chat.title}</strong><small>{new Date(chat.updatedAt).toLocaleDateString()}</small></button>}<span className="chat-actions"><button onClick={()=>beginRename(chat.id,chat.title)} title="Rename"><Pencil size={14}/></button><button onClick={()=>void removeChat(chat.id)} disabled={busy===chat.id} title="Delete"><Trash2 size={14}/></button></span></div>)}</div><div className="sidebar-bottom"><button className="profile-button" onClick={()=>nav("account")}><span className="avatar-small">{(user?.displayName||user?.email||"U").slice(0,1).toUpperCase()}</span><span className="profile-copy"><strong>{user?.displayName||"My account"}</strong><small>{user?.email}</small></span></button><button className="sidebar-setting" onClick={onSettings}><Settings size={18}/><span>Settings</span></button><button className="sidebar-setting danger" onClick={()=>void signOutUser()}><LogOut size={18}/><span>Log out</span></button></div></aside>;
}
