import type { VercelRequest, VercelResponse } from "@vercel/node";
type Role = "user" | "assistant" | "system";
type ChatMessage = { role: Role; content: string };
type RequestBody = { message?: string; messages?: ChatMessage[]; history?: ChatMessage[] };
const SYSTEM_PROMPT = `You are DOG, a helpful AI assistant. For coding requests, collaborate first when requirements are unclear, then provide accurate working code. Use readable markdown. Never mention internal providers, APIs, routing, model names, or environment variables.`;
function normalize(body:RequestBody):ChatMessage[]{const source=Array.isArray(body.messages)&&body.messages.length?body.messages:body.history;if(Array.isArray(source)&&source.length)return source.filter(m=>m&&typeof m.content==="string"&&["user","assistant","system"].includes(m.role)).slice(-20);if(typeof body.message==="string"&&body.message.trim())return[{role:"user",content:body.message.trim()}];return[];}
function payload(messages:ChatMessage[]){return[{role:"system",content:SYSTEM_PROMPT},...messages.filter(m=>m.role!=="system")];}
async function xai(messages:ChatMessage[]){const key=(process.env.XAI_API_KEY||process.env.GROK_API_KEY)?.trim();if(!key)throw new Error("DOG Engine is not configured.");const model=(process.env.XAI_TEXT_MODEL||process.env.GROK_TEXT_MODEL)?.trim()||"grok-4-1-fast-reasoning";const r=await fetch("https://api.x.ai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:payload(messages),temperature:.4,max_tokens:8192})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`DOG Engine ${r.status}: ${d?.error?.message||"Request failed"}`);const text=d?.choices?.[0]?.message?.content;if(typeof text!=="string"||!text.trim())throw new Error("DOG Engine returned an empty response.");return text;}
async function openAICompatible(messages:ChatMessage[]){const base=process.env.DOG_ENGINE_BASE_URL?.trim();const key=process.env.DOG_ENGINE_API_KEY?.trim();const model=process.env.DOG_ENGINE_MODEL?.trim();if(!base||!model)throw new Error("DOG Engine endpoint is not configured.");const headers:Record<string,string>={"Content-Type":"application/json"};if(key)headers.Authorization=`Bearer ${key}`;const r=await fetch(`${base.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers,body:JSON.stringify({model,messages:payload(messages),temperature:.4,max_tokens:8192})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`DOG Engine ${r.status}: ${d?.error?.message||"Request failed"}`);const text=d?.choices?.[0]?.message?.content;if(typeof text!=="string"||!text.trim())throw new Error("DOG Engine returned an empty response.");return text;}
async function gemini(messages:ChatMessage[]){const key=process.env.GEMINI_API_KEY?.trim();if(!key)throw new Error("DOG Engine is not configured.");const model=process.env.GEMINI_TEXT_MODEL||"gemini-2.5-flash";const contents=messages.filter(m=>m.role!=="system").map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({systemInstruction:{parts:[{text:SYSTEM_PROMPT}]},contents,generationConfig:{temperature:.4,maxOutputTokens:8192}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`DOG Engine ${r.status}: ${d?.error?.message||"Request failed"}`);const text=d?.candidates?.[0]?.content?.parts?.map((p:{text?:string})=>p.text||"").join("")||"";if(!text.trim())throw new Error("DOG Engine returned an empty response.");return text;}
export default async function handler(req:VercelRequest,res:VercelResponse){if(req.method!=="POST")return res.status(405).json({ok:false,error:"Method not allowed"});try{const messages=normalize((req.body||{}) as RequestBody);if(!messages.length)return res.status(400).json({ok:false,error:"A message is required."});let text:string;const errors:string[]=[];for(const fn of [xai,openAICompatible,gemini]){try{text=await fn(messages);return res.status(200).json({ok:true,text});}catch(e){errors.push(e instanceof Error?e.message:"Request failed");}}return res.status(502).json({ok:false,error:errors.at(-1)||"DOG could not get a response."});}catch(e){return res.status(502).json({ok:false,error:e instanceof Error?e.message:"DOG could not get a response."});}}
